name: Exercise 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test
        working-directory: exercise1/rust

      - name: Set up PostgreSQL client
        uses: docker://postgres:latest

      - name: Write data to DB
        if: success()
        env:
          PGHOST: ${{ secrets.DB_HOST }}
          PGPORT: ${{ secrets.DB_PORT }}
          PGUSER: ${{ secrets.DB_USER }}
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGDATABASE: ${{ secrets.DB_NAME }}
        run: psql -c "INSERT INTO scoreboard (team, exercise) VALUES ('team2',2);"