name: Exercise 3

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --node
        working-directory: exercise3

      - name: Set up  and start PostgreSQL client
        run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib
          sudo systemctl start postgresql.service

      - name: Write data to DB
        #if: success()
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
        run: |
          echo Extracting the team name from the branch name and inserting into db
          psql -c "INSERT INTO scoreboard (team, exercise) VALUES ('${GITHUB_REF##*/}',3) ON CONFLICT DO NOTHING;" 